name: test
run-name: ${{ github.actor }} is testing
on: [push]

jobs:
  micromamba-test:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: docker/setup-buildx-action@v2
      - name: test
        run: |
          docker run mambaorg/micromamba:latest micromamba install -y make
